# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: eunha's diary
email: lee95625@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  음 이거 마음엔 안 들지만 잠시 써볼까나 ㅇㅅaㅇ
baseurl: "/sapjil" # the subpath of your site, e.g. /blog
url: "http://emellen.com" # the base hostname & protocol for your site
twitter_username: mrn_galaxy
github_username: lee10104 

# Build settings
markdown: kramdown
